/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("InvoiceHeaderObjectPageObjectPage journey");

        opaTest("Navigate to InvoiceHeaderObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheInvoiceHeaderList.onFilterBar().iExecuteSearch();

            Then.onTheInvoiceHeaderList.onTable().iCheckRows();
            When.onTheInvoiceHeaderList.onTable().iPressRow(0);

            Then.onTheInvoiceHeaderObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheInvoiceHeaderObjectPage.onHeader().iCheckHeaderFacet({ facetId: "HeaderData" });
            Then.onTheInvoiceHeaderObjectPage.onHeader().iCheckHeaderFacet({ facetId: "GrossAmount" });
            Then.onTheInvoiceHeaderObjectPage.onHeader().iCheckHeaderFacet({ facetId: "Confidence" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheInvoiceHeaderObjectPage.iCheckNumberOfSections(5);
            When.onTheInvoiceHeaderObjectPage.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheInvoiceHeaderObjectPage.iCheckSection({ section: "GeneralInfo" });
            When.onTheInvoiceHeaderObjectPage.iPressSectionIconTabFilterButton("Amounts");
            Then.onTheInvoiceHeaderObjectPage.iCheckSection({ section: "Amounts" });
            When.onTheInvoiceHeaderObjectPage.iPressSectionIconTabFilterButton("Payment");
            Then.onTheInvoiceHeaderObjectPage.iCheckSection({ section: "Payment" });
            When.onTheInvoiceHeaderObjectPage.iPressSectionIconTabFilterButton("ErrorDetails");
            Then.onTheInvoiceHeaderObjectPage.iCheckSection({ section: "ErrorDetails" });
            When.onTheInvoiceHeaderObjectPage.iPressSectionIconTabFilterButton("AuditInfo");
            Then.onTheInvoiceHeaderObjectPage.iCheckSection({ section: "AuditInfo" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});