/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("InvoiceHeaderListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheInvoiceHeaderList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheInvoiceHeaderList.onFilterBar().iCheckFilterField("Single-Character Flag");
            Then.onTheInvoiceHeaderList.onFilterBar().iCheckFilterField("Supplier");
            Then.onTheInvoiceHeaderList.onFilterBar().iCheckFilterField("Company Code");
            Then.onTheInvoiceHeaderList.onFilterBar().iCheckFilterField("Reference");
            Then.onTheInvoiceHeaderList.onFilterBar().iCheckFilterField("Posting Date");
            Then.onTheInvoiceHeaderList.onFilterBar().iCheckFilterField("Time Stamp");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheInvoiceHeaderList.onTable().iCheckColumns(9, {"Status":{"header":"Single-Character Flag"},"InvoiceNumber":{"header":"Reference"},"VendorNumber":{"header":"Supplier"},"CompanyCode":{"header":"Company Code"},"GrossAmount":{"header":"Amount"},"PostingDate":{"header":"Posting Date"},"SapDocument":{"header":"Document Number"},"ErrorMessage":{"header":"Char255"},"CreatedAt":{"header":"Time Stamp"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheInvoiceHeaderList.onFilterBar().iExecuteSearch();
            
            Then.onTheInvoiceHeaderList.onTable().iCheckRows();

            When.onTheInvoiceHeaderList.onTable().iPressRow(0);
            Then.onTheInvoiceHeaderObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});